apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: sahilrajput03/dwk-4-gitops-app
  newTag: ba4fea12c011f90a75ca7f22771c4a1ff292977c
