# `kind: job` are also available: Read @ https://kubernetes.io/docs/concepts/workloads/controllers/job/
apiVersion: batch/v1
kind: Job
metadata:
  name: daily-todos
  namespace: default
  labels:
    run: curl
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:7.73.0
          args:
            - sh
            - -c
            - "echo -n 'Read: '; curl -sI https://en.wikipedia.org/wiki/Special:Random |grep 'location:' |awk '{print $2}'"
      restartPolicy: OnFailure
