apiVersion: batch/v1
kind: Job
metadata:
  name: backup
spec:
  template:
    spec:
      containers:
      - name: backup
        image: jakousa/simple-backup-example
        env:
          - name: URL
            value: "postgres://postgres:example@postgres-svc:5432/postgres"
            # value: "postgres://postgres:example@postgres-svc.default:5432/postgres"
            # FYI: .default seems to be causing problem, so removed it! ~ Sahil
      restartPolicy: Never # This time we'll run it only once
