apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- secret.yaml
- deployment.yaml
images:
- name: IMAGE_BROADCASTER
  newName: sahilrajput03/broadcaster-project
  # newTag: latest
