apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# We can point to other kustomization directories, src: https://stackoverflow.com/a/67543731/10012446
resources:
- statefulset.yaml
- configmap.yaml
- persistentvolumeclaim.yaml
- ingress.yaml
- persistentvolume.yaml
- service.yaml
- ../broadcaster-with-manifests/manifests

# You can check if the below values are utilized properly via `kc kustomize` command. YO!


images:
- name: PROJECT_BACKEND
  newName: sahilrajput03/ex2-02-img
  newTag: 5ec66211c930f2b7ab7a3d17465853967db31cc8
- name: PROJECT_FRONTEND
  newName: sahilrajput03/project1-img
  newTag: 37510fec42df3676ea56f6eb4cef6335a8a8df98
