apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project1-claim
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
