apiVersion: apps/v1
# kind: Deployment
kind: StatefulSet
metadata:
  name: mongo-pingpong-ss
spec:
  serviceName: mongo1-svc
  replicas: 1
  # replicas: 2
  selector:
    matchLabels:
      app: mongo-pingpong-app

  template:
    metadata:
      labels:
        app: mongo-pingpong-app
    spec:
      containers:
        - name: db
          image: mongo
          ports:
            - name: db
              containerPort: 27017
          volumeMounts:
            # mountpoint to store pg data
            - name: mongo-vol
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-vol
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1 # Includes the Service for lazyness
kind: Service
metadata:
  name: mongo1-svc
  # labels:
  #   app: pingpong-app
  # uncommenting above labels in favor of moritz configuration!
spec:
  ports:
    - port: 27017
      name: web
  clusterIP: None
  selector:
    app: mongo-pingpong-app
    # ^^^ fyi: Any service uses this selector to know which pod it should connect to!, src:(comment on this answer) https://stackoverflow.com/a/57666034/10012446
