name: Release 4-gitops-app

  ##### ABOUT `flux`
  # FYI: I have my flux configuration repo @ https://github.com/sahilrajput03/kube-cluster-dwk.
  # which was cretead automatically with command: 
  # `flux bootstrap github --owner=sahilrajput03 --repository=kube-cluster-dwk --personal --private=false`
  #
  # Also, in above repo I added two files `example.yml` and `example-kustomization.yml` files to poll docker hub for new images at interval of 10 minutes continuously.
  #####

on:
  push:
    branches:
      # ORIGINALLY
      # - master
      - main
    paths:
      - '4-gitops/app/**'
      - '.github/workflows/gitops-app.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # To  use simple build process with just docker i.e., without the qemu and `setup-build-action` action, you must look @ https://devopswithkubernetes.com/part-4/3-gitops .
    - name: Prepare
      id: prep
      run: |
        # originally #DOCKER_IMAGE=jakousa/dwk-4-gitops-app
        DOCKER_IMAGE=sahilrajput03/dwk-4-gitops-app
        # Set the platforms to build for here and thus reduce duplicating it.
        PLATFORMS=amd64,arm,arm64
        TAGS="${DOCKER_IMAGE}:${{ github.sha }}"
        # Set output parameters.
        if [ "${{github.event_name}}" == "pull_request" ]; then
          echo ::set-output name=push::false
        else
          echo ::set-output name=push::true
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
        fi
        echo ::set-output name=platforms::${PLATFORMS}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ steps.prep.outputs.platforms }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:latest

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: 4-gitops/app
        platforms: ${{ steps.prep.outputs.platforms }}
        push: ${{ steps.prep.outputs.push }}
        tags: ${{ steps.prep.outputs.tags }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: 4-gitops/manifests
      run: |-
        # originally # kustomize edit set image IMAGE_PLACEHOLDER=jakousa/dwk-4-gitops-app:${{ github.sha }}
        kustomize edit set image IMAGE_PLACEHOLDER=sahilrajput03/dwk-4-gitops-app:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: '4-gitops/manifests/kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        # ~Sahil, This is a builtin secret, you don't need to add this token at all. Src: https://docs.github.com/en/github-ae@latest/actions/security-guides/automatic-token-authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
