name: Release project-frontend

on:
  push:
    branches:
      # ORIGINALLY
      # - master
      - main
    paths:
      - '.github/workflows/project-frontend.yml'
      - './exercises/ex4-08/ex4-06/ex2-08-statefulsets/project1/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # To  use simple build process with just docker i.e., without the qemu and `setup-build-action` action, you must look @ https://devopswithkubernetes.com/part-4/3-gitops .
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=sahilrajput03/project1-img
        # Set the platforms to build for here and thus reduce duplicating it.
        PLATFORMS=amd64,arm,arm64
        TAGS="${DOCKER_IMAGE}:${{ github.sha }}"
        # Set output parameters.
        if [ "${{github.event_name}}" == "pull_request" ]; then
          echo ::set-output name=push::false
        else
          echo ::set-output name=push::true
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
        fi
        echo ::set-output name=platforms::${PLATFORMS}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ steps.prep.outputs.platforms }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:latest

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: 4-gitops/app
        platforms: ${{ steps.prep.outputs.platforms }}
        push: ${{ steps.prep.outputs.push }}
        tags: ${{ steps.prep.outputs.tags }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: exercises/ex4-08/ex4-06/ex2-08-statefulsets/manifests
      run: |-
        # originally # kustomize edit set image IMAGE_PLACEHOLDER=jakousa/dwk-4-gitops-app:${{ github.sha }}
        kustomize edit set image PROJECT_FRONTEND=sahilrajput03/project1-img:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'exercises/ex4-08/ex4-06/ex2-08-statefulsets/ex2-02/manifests/kustomization.yml'
        message: New version release for project-frontend ${{ github.sha }}
      env:
        # ~Sahil, This is a builtin secret, you don't need to add this token at all. Src: https://docs.github.com/en/github-ae@latest/actions/security-guides/automatic-token-authentication
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
